version: '3.1'
services:
  smart-context:
    image: smart-context
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - .:/app
    environment:
    - ISSUER=http://localhost:9200/smartauth
    - SCOPES="launch context"
    - AUDIENCE=authserver
    - API_KEY=e7ce47e88053fa31998de414423e82c47fd479688be5ad8dd9ecc0ac61108a8b
