version: '3.1'
services:
  smart-context:
    container_name: smart-context
    image: smart-context
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - .:/app
    environment:
    - ISSUER=${ISSUER}
    - JWKS_URI=${JWKS_URI}
    - SCOPES=${SCOPES}
    - API_KEY=${API_KEY}