version: '3.1'
services:
  smart-context:
    image: smart-context
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - .:/app
    environment:
    - ISSUER_URI=http://localhost:8080/auth/realms/smart-context
    - JWKS_URI=http://localhost:8080/auth/realms/smart-context/protocol/openid-connect/certs
    - SCOPES=openid smart-context
    - AUDIENCE=smart-context
